config/routes.rb
Rails.application.routes.draw do
  get "tags/create"
  get :search, controller: :main
  devise_for :users, controllers: {omniauth_callbacks: "omniauth_callbacks"}
  root "static_page#index"
  resources :posts do
    resources :comments
  end
  mount RailsAdmin::Engine => "/admin", as: "rails_admin"

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many :post_tags, dependent: :destroy
  has_many :tags, through: :post_tags
  has_many :comments, dependent: :destroy

  scope :sort_by_time, ->{order created_at: :desc}

  mount_uploader :image, ImageUploader

  def all_tags= names
    self.tags = names.split(",").map do |name|
      Tag.where(name: name.strip).first_or_create!
    end
  end

  def all_tags
    self.tags.map(&:name).join(", ")
  end
end

app/models/post_tag.rb
class PostTag < ApplicationRecord
  belongs_to :post, foreign_key: :post_id
  belongs_to :tag, foreign_key: :tag_id
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :follower, class_name: User.name
  belongs_to :followed, class_name: User.name
end

app/models/tag.rb
class Tag < ApplicationRecord
  has_many :post_tags, dependent: :destroy
  has_many :posts, through: :post_tags
end

app/models/user.rb
class User < ApplicationRecord
  has_many :posts, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :active_relationships, class_name: Relationship.name,
    foreign_key: :follower_id, dependent: :destroy
  has_many :passive_relationships, class_name: Relationship.name,
    foreign_key: :follower_id, dependent: :destroy
  has_many :following, through: :active_relationships, source: :followed
  has_many :followers, through: :passive_relationships, source: :follower

  devise :database_authenticatable, :registerable, :omniauthable,
    :recoverable, :rememberable, :trackable, :validatable

  def self.from_omniauth auth
    User.find_or_initialize_by(email: auth.info.email).tap do |user|
      user.name = auth.info.name
      user.provider = auth.provider
      user.uid = auth.uid
      user.email = auth.info.email
      user.image = auth.info.image
      user.password = User.generate_unique_secure_token if user.new_record?
      user.save
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :correct_user, only: [:update, :edit, :destroy]
  before_action :load_post, only: [:create, :update, :destroy, :edit]

  def create
    @comment = @post.comments.build comment_param
    if @comment.save
      flash[:success] = t "devise.comment.commented"
      redirect_to @post
    else
      flash[:warning] = t "devise.comment.opp"
      redirect_to @post
    end
  end

  def edit
  end

  def update
    if @comment.update_attributes comment_param
      flash[:success] = t "devise.comment.edited"
      redirect_to @post
    else
      flash[:warning] = t "devise.comment.opp"
      redirect_to root_path
    end
  end

  def destroy
    if @comment.destroy
      flash[:success] = t "devise.comment.deleted"
      redirect_to @post
    else
      flash[:warning] = t "devise.comment.opp"
      redirect_to root_path
    end
  end

  private

  def comment_param
    params.require(:comment).permit :user_id, :content
  end

  def load_post
    @post = Post.find_by id: params[:post_id]
    render "public/404.html" unless @post
  end

  def correct_user
    @comment = current_user.comments.find_by id: params[:id]
    render "public/404.html" unless @comment
  end
end

app/controllers/omniauth_callbacks_controller.rb
class OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    @user = User.from_omniauth request.env["omniauth.auth"]
    if @user.persisted?
      sign_in_and_redirect @user, event: :authentication
      set_flash_message(:notice, :success, kind: "Facebook") if
        is_navigational_format?
    else
      session["devise.facebook_data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
  end

  def google_oauth2
    @user = User.from_omniauth request.env["omniauth.auth"]
    if @user.persisted?
      flash[:notice] = I18n.t "devise.omniauth_callbacks.success", kind: "Google"
      sign_in_and_redirect @user, event: :authentication
    else
      session["devise.google_data"] = request.env["omniauth.auth"].except(:extra)
      redirect_to new_user_registration_url, alert: @user.errors.full_messages.join("\n")
    end
  end

  def failure
    redirect_to root_path
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :user_signed?, except: :index
  before_action :correct_user, only: [:edit, :destroy, :update]
  before_action :set_post, only: :show
  
  def index
    @posts = Post.all.sort_by_time.page(params[:page]).
      per Settings.post.perpage
  end

  def show
    @comment = Comment.new
    @comments = @post.comments
  end

  def new
    @post = Post.new
  end

  def edit
  end

  def create
    @post = current_user.posts.build post_params
    respond_to do |format|
      if @post.save
        format.html {redirect_to @post, notice: t("devise.post.post_created") }
        format.json {render :show, status: :created, location: @post}
      else
        format.html {render :new}
        format.json {render json: @post.errors, status: :unprocessable_entity}
      end
    end
  end

  def update
    respond_to do |format|
      if @post.update post_params
        format.html {redirect_to @post, notice: t("devise.post.post_updated")}
        format.json {render :show, status: :ok, location: @post}
      else
        format.html {render :edit}
        format.json {render json: @post.errors, status: :unprocessable_entity}
      end
    end
  end

  def destroy
    @post.destroy
    respond_to do |format|
      format.html {redirect_to posts_url, notice: t("devise.post.post_destroy")}
      format.json {head :no_content}
    end
  end

  private
  def set_post
    @post = Post.find_by id: params[:id]
  end

  def post_params
    params.require(:post).permit :title, :content, :picture, :tag_list
  end

  def user_signed?
    redirect_to new_user_session_path unless user_signed_in?
  end

  def correct_user
    @post = current_user.posts.find_by id: params[:id]
  end
end

app/controllers/static_page_controller.rb
class StaticPageController < ApplicationController
  def index
    if user_signed_in?
      redirect_to posts_path
    else
      redirect_to new_user_session_path
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def tag_cloud tags, classes
    max = tags.sort_by(&:count).last
    tags.each do |tag|
      index = tag.count.to_f / max.count * (classes.size - 1)
      yield(tag, classes[index.round])
    end
  end

  def load_user resource
    User.pluck(:name).where id: resource.user_id
  end
end

app/helpers/post_helper.rb
module PostHelper
  included "UserHelper"
  def load_user post
    User.find_by id: post.user_id
  end

  def correct_user source
    current_user !=nil && current_user.id == source.user_id
  end
end

app/helpers/user_helper.rb
module UserHelper
  def load_value_form resource
    if resource.pending_reconfirmation?
      resource.unconfirmed_email
    else
      resource.email
    end
  end

  def gravatar_for user, options = {size: Settings.user.avatar}
    gravatar_id = Digest::MD5.hexdigest user.email.downcase
    size = options[:size]
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag gravatar_url, alt: user.name, class: "gravatar avatar"
  end
end

app/views/comments/_comment.erb
<tr>
  <td width="10%">
    <%= load_user(comment).name %>
  </td>
  <td width="80%">
    <%= comment.content %>
  </td>
  <td width="10%">
  <% if correct_user comment %>
    <%= link_to t("devise.registrations.edit.edit"), edit_post_comment_path(@post, comment) %>
    <%= link_to t("devise.registrations.edit.destroy"), post_comment_path(@post, comment), method: :delete,
      confirm: t("devise.registrations.edit.sure") %>
  <% end %>
  </td>
</tr>

app/views/comments/_form.html.erb
<%= form_for [post, comment]  do |f| %>
  <%= hidden_field_tag "comment[user_id]", current_user.id %>
  <%= f.text_field :content, class: "form-control" %>
  <%= f.submit t"devise.passwords.new.comment" %>
<% end %>

app/views/comments/edit.html.erb
<h1><%= t "devise.registrations.edit.editpost" %></h1>
<%= render "comments/form", post: @post, comment: @comment %>

app/views/layouts/_footer.html.erb
<footer>
  <div class="container">
    <div class="units-row">
      <div class="unit-50">
        <button class="btn btn-black"><i class="fa fa-arrow-left"></i> PREVIOUS</button>
      </div>
      <div class="unit-50">
        <ul class="social list-flat right">
          <li><a href="mailto:afnizarhilmi@gmail.com"><i class="fa fa-send"></i></a></li>
          <li><a href="http://twitter.com/flamekaizar"><i class="fa fa-twitter"></i></a></li>
          <li><a href="http://dribbble.com/flamekaizar"><i class="fa fa-dribbble"></i></a></li>
          <li><a href="http://behance.com/flamekaizar"><i class="fa fa-behance"></i></a></li>
        </ul>
      </div>
    </div>
    <p class="text-centered foot-cp">
      <a href="#">handcrafted by @flamekaizar</a>
    </p>
  </div>
</footer>

app/views/layouts/_header.html.erb
<div class="main-nav">
  <div class="container">
    <header class="group top-nav">
      <nav class="navbar logo-w navbar-left" >
        <a class="logo" href="index.html">Blog</a>
      </nav>
      <div class="navigation-toggle" data-tools="navigation-toggle" data-target="#navbar-1">
        <span class="logo">Blog</span>
      </div>
      <nav id="navbar-1" class="navbar item-nav navbar-right">
        <ul>
          <li class="active"><%= link_to "Home", root_path %></li>
          <li><%= link_to "Post", posts_path %></li>
          <li><%= link_to "Login", new_user_session_path %></li>
          <li><%= link_to "Log out", destroy_user_session_path, method: :delete%></li>
        </ul>
      </nav>
    </header>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BL</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbolinks-track": "reload" %>

  </head>
  <body>
  <%= render "layouts/header" %>
    <%= yield %>
  <%= render "layouts/footer" %>
  </body>
</html>

app/views/posts/_form.html.erb
<div class="container">
  <%= form_for post, local: true do |form| %>
    <% if post.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

        <ul>
          <% post.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
    <%= form.text_field :title, class: "form-control", placeholder: "Tỉtle" %>
    <%= form.text_field :tag_list, class: "form-control", placeholder: "Tag
  list" %>
    <%= form.text_area :content, class: "form-control", placeholder: "Content" %>
    <%= form.file_field :picture, class: "btn btn-warning", placeholder:
      "Title" %>
    <div class="actions">
      <%= form.submit "Create", class: "btn btn-primary" %>
    </div>
  <% end %>
</div>

app/views/posts/_post.html.erb
<div class="post">
  <h1>
    <%= link_to post.title, post %>
  </h1>
  <hr>
  <div class="in-content">
    <p>
      <%= post.content %>
    </p>
    <%= link_to "Read more", post, class: "read-more" %>
  </div>
  <div class="foot-post">
    <div class="units-row">
      <div class="unit-100">
        <strong>Tags:</strong>
          <% if post.tags.any? %>
            <% post.tags.each do |tag| %>
              <%= link_to tag.name %>
            <% end %>
          <% end %>
      </div>
    </div>
  </div>
</div>

app/views/posts/index.html.erb
<div class="intro">
  <div class="container">
    <div class="units-row">
      <div class="unit-10">
        <%= image_tag("avatar.png", class: "img-intro")  %>
      </div>
      <div class="unit-90">
        <p class="p-intro">Hello, I’m Intern. I’m proud to be a part of milky
          way.</p>
      </div>
    </div>
  </div>
</div>
<div class="content">
  <div class="container">
    <%= render @posts %>
  </div>
</div>
<%= paginate @posts %>

app/views/posts/new.html.erb
<h1>New Post</h1>
<%= render "form", post: @post %>
<%= link_to "Back", posts_path %>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>
<div class="container">
  <table class="table table-striped">
    <tr>
      <td>
        <%= @post.title %>
      </td>
    </tr>
    <tr>
      <td>
        <%= @post.content %>
      </td>
    </tr>
  </table>

<% if correct_user @post %>
  <%= link_to t("devise.registrations.edit.edit"), edit_post_path(@post) %> |
  <%= link_to t("devise.registrations.edit.back"), posts_path %>
<% end %>
<table class="table-striped table">
    <%= render @comments %>
</table>
<%= render "comments/form", post: @post, comment: @comment %>
</div>

app/views/users/shared/_links.html.erb
<%- if controller_name != "sessions" %>
  <%= link_to t("users.sessions.new.login"), new_session_path resource_name %>
  <br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != "registrations" %>
  <%= link_to t("users.registrations.new.sign_up"),
    new_registration_path resource_name %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != "passwords" && controller_name != "registrations" %>
  <%= link_to t("users.passwords.new.forgot"),
    new_password_path resource_name %>
  <br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != "confirmations" %>
  <%= link_to t(".didnot_receive_confirm"),
    new_confirmation_path resource_name %>
  <br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != "unlocks" %>
  <%= link_to t(".didnot_receive_unlock"), new_unlock_path resource_name %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to t(".sign_in_with", provider: OmniAuth::Utils.camelize(provider)),
      omniauth_authorize_path(resource_name, provider)
    %><br />
  <% end -%>
<% end -%>